Pin to Python 3.10 for compatibility reasons
the pinned version of pylint fails because
```
ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py)
```